
  
  export  const CUSTOMER_DATA_LOADING =   "CUSTOM_DATA_LOADING";
  export  const CUSTOMER_DATA_FETCHED = "CUSTOMER_DATA_FETCHED";
  export  const CUSTOMER_DATA_FAILED  = "CUSTOMER_DATA_FAILED";

  export  const CUSTOMER_SEARCH_FETCHED =  "CUSTOMER_SEARCH_FETCHED";
  export  const CUSTOMER_SEARCH_LOADING =  "CUSTOMER_SEARCH_LOADING";
  export  const CUSTOMER_SEARCH_FAILED =  "CUSTOMER_SEARCH_FAILED";

  

  export const ADD_CUSTOMER = "ADD_CUSTOMER"
  export const EDIT_CUSTOMER = "EDIT_CUSTOMER"

  export const CUSTOMER_SEARCH_NAME = "CUSTOMER_SEARCH_NAME"


